### ISSUE TITLE
Split Language.Haskell.TH.Lens into own package

### ISSUE THREAD

**Issue by phadej** [ekmett/lens#844]
`template-haskell` may (and will with GHC-8.8.1) introduce breaking changes, which isn't possible to shim across `template-haskell`s bundled with GHC that `lens` support.

I suggest splitting that package out.
I think that `lens` itself does use something from there for `makeLenses` etc. machinery, but those bits doesn't need to be in the public interface.

**Comment by RyanGlScott** [comment]
I tentatively support this idea, if only for the very practical reason that any breaking API change to `template-haskell` essentially requires `lens` to propagate those same changes to `Language.Haskell.TH.Lens`, which itself requires a major version bump to `lens`. A side effect of this is that we have to crank out major versions of `lens` for every new version of GHC that is released, which feels rather silly.

**Comment by RyanGlScott** [comment]
Assuming that we do wish to split off `Language.Haskell.TH.Lens`, what name should this hypothetical package have? `template-haskell-lens`? `lens-th`? Something else?

**Comment by phadej** [comment]
I like both lens-th and template-haskell-th; lens-th sounds like package to derive lens with th though. lens-template-haskell feels wrong.

So: template-haskell-lens

**Comment by glguy** [comment]
Not that it makes it easier to pick but we also have `lens-aeson` out there

**Comment by phadej** [comment]
- https://hackage.haskell.org/package/zlib-lens
- https://hackage.haskell.org/package/writer-cps-lens
- https://hackage.haskell.org/package/xml-html-conduit-lens
- https://hackage.haskell.org/package/hreader-lens
- https://hackage.haskell.org/package/time-lens

but

- https://hackage.haskell.org/package/lens-toml-parser
- https://hackage.haskell.org/package/lens-datetime
- https://hackage.haskell.org/package/lens-xml

---

I personally favour `$packagename-lens` naming; yet for `servant` we use `servant-$pkgname`. In anyway, consistency in `lens`-land is far sailed ship :)

**Comment by fumieval** [comment]
FWIW, lens-aeson is named so because there was already aeson-lens which is unlawful

**Comment by Taneb** [comment]
I'm strongly in favour of `template-haskell-lens`

**Comment by glguy** [comment]
Should we orphan the `Plated` instances into this new package?

**Comment by glguy** [comment]
WIP https://github.com/glguy/template-haskell-lens

**Comment by Taneb** [comment]
@glguy I was assuming we were just moving `Language.Haskell.TH.Lens`, I'm not sure splitting off `Control.Lens.TH` is necessary or even desirable: they're useful tools we want almost whenever we use `lens`

**Comment by RyanGlScott** [comment]
I've just created ekmett/lens#852 and lens/template-haskell-lens#1 which migrate `Language.Haskell.TH.Lens`. Since this only migrates `Language.Haskell.TH.Lens`, I needed to make some changes to the `lens` internals to make up for `Language.Haskell.TH.Lens`'s absence. Feedback is appreciated.

**Comment by RyanGlScott** [comment]
So I talked with @ekmett about this plan this morning, and he wasn't enthusiastic about the idea:

```
07:05:07 <RyanGlScott> Do you support this direction of travel? https://github.com/ekmett/lens/pull/852
07:05:23 <edwardk> not really =/
07:05:36 <RyanGlScott> OK, this is why I hesitated to merge this
07:06:13 <edwardk> it brings in all of the issues with users needing multiple deps, etc. to do anything and there are already a half dozen lens lights that all have their own th support
07:06:25 <RyanGlScott> If you get a chance, could you write a comment saying as much on the relevant issue? Then, when I close it, that would make it more obvious why I did so
07:07:22 <edwardk> if we had a small enough support window that we could limit ourselves to something with reexported-modules there might be a story for it, but then we're far enough along that multiple libs is close, and lens:th or something could be a much smaller dependency
```

In light of this, I'm inclined to close this issue as wontfix.

**Comment by phadej** [comment]
Than we are in beginning square with how to deal with incompatible API in Language.Haskell.TH.Lens

The right approaches are
- limit template-haskell to 8.8 bundled one
- remove non-shimmable/incompatible symbols

And the “wrong” (violates PVP) approach would be:
- let `lens` API depend on template-haskell version
- if this is chosen, that should be clearly marked in both the module and affected symbols documentation

**Comment by RyanGlScott** [comment]
For better or worse, the approach that `lens` currently adopts is the latter one. As I've mentioned above, I don't think the former approach is either feasible or desirable.

I agree that we should more clearly advertise the fact that the `Language.Haskell.TH.Lens` API mirrors that of `Language.Haskell.TH`, even down to incompatibilities between `template-haskell` versions.

**Comment by ocharles** [comment]
I personally prefer lens-template-haskell, as template-haskell-lens sounds like lenses *for* template-haskell.

I care less about the name though than this actually happening. The major release cadence of lens is too high for my liking, anything that reduces it is a good thing imo.

**Comment by Taneb** [comment]
@ocharles I understood that the proposal here is to split off precisely the lenses for template-haskell, rather than the template haskell for lens (in C.L.TH)

**Comment by ocharles** [comment]
Oh, then in that case the name is good!

**Comment by ekmett** [comment]
> let `lens` API depend on template-haskell version 
> - if this is chosen, that should be clearly marked in both the module and affected symbols documentation

That is acceptable to me. The `Language.Haskell.TH` module is particularly egregious in how much it changes based on the upstream version.

But note this already happens in a ton of small ways all over the package. Here for the most part you can't really use the lenses into template-haskell without actually incurring a dependency on `template-haskell` yourself at which point you're mostly locked in.

The idea that my version is enough for you to know exactly what API i'll give you doesn't really work when I have to link against 1-10 versions of a dozen different packages each. There are almost 500 `#ifdef`s scattered throughout lens. A non-zero fraction of them are API facing.

e.g. 

* Tied to the `__GLASGOW_HASKELL__ >= 710` there are pattern synonyms strewn everywhere through the entire API.

* `Control.Exception.Lens` exposes `AsCompactionFailed(_CompactionFailed)` on `base >= 4.10`. There are tons of examples like this of data types that didn't exist getting support either through instances of custom optics. e.g. we have a metric boatload of Wrapped instances for arcane things like `HTYPE_KEY_T`, etc, that vary based on platform as to their availability.

* If we're on ghcjs or mingw32 we don't supply instances `AsEmpty GHC.Event.Event`.

* `Trustworthy` vs. `SafeHaskell` flails all over the place because it is impossible to state cleanly -- ironically because it depends on the details of packages that haven't even been written yet and not just those packages but all the details of every valid combination their upstream dependencies, whether or not they agree to SafeHaskell standards, it affects me.

If no API changes based on upstream dependency bound changes is a goal of the PVP then I'm just going to be out of compliance with the PVP as it simply isn't possible to maintain code with any sort of support window and comply with that goal. =/

As for general package naming. I also prefer `foo-lens` to `lens-foo`. With respect to `lens-aeson`, that one was forced on us by `aeson-lens` already existing with an unusable API. I hesitate to use it as a precedent for further developments.
