### ISSUE TITLE
There's no toListOf for MonadState

### ISSUE THREAD

**Issue by ssadler** [ekmett/lens#891]
It seems like a combination of `use` and `toListOf` would be useful for the case of getting the values accessed by a traversal as a list in the context of MonadState. For example:
```haskell
useList :: MonadState s m => Traversal' s a -> m [a] 
```
This seems like a fairly simple use case and I didn't find it as part of the Lens API. The reason I think this might be good to have is that the lack of it's existence is surprising. Lens provides both  `^..` and `toListOf` for non monadic usage, so it's easy to assume that the use case should be covered for within `StateT`.

**Comment by stevenfontanella** [comment]
I also think this would be a good addition, something like:

```haskell
useAll :: MonadState s m => Getting (Endo [a]) s a -> m [a]
useAll traversal = do
  s <- get
  pure $ s ^.. traversal
```

Otherwise it's a bit noisy to write the above two lines (or `toListOf traversal <$> get`) every time. Can we consider adding it, or is it too small to justify?

**Comment by ekmett** [comment]
`useAll` or `useList` is the same as `use . partsOf`, which seems, by definition to be below the Fairbairn threshold. 

Now, generally the `lens` library defines lots of combinators that would otherwise violate this rule, so that isn't a slam dunk against providing this functionality.

What does seem to indicate we shouldn't bother packaging this is that the direct definition there seems to imply the lensy name should be `usePartsOf`, but we don't go and define `useX` for any other `x` combinator in `lens`, outside of the various operators, e.g. `%~` vs. `%=` where the usage pattern would be onerous.
