### ISSUE TITLE
Kind and type vars sometimes out of dependency order with makePrisms/makeLenses

### ISSUE THREAD

**Issue by jamespayor** [ekmett/lens#917]
I ran into an obscure issue with the `makePrisms`/`makeLenses` TH, which occurs when the kinds of different type variables are related.

Compiling the following:

```haskell
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PolyKinds #-}
module Test where
import Control.Lens

data Foo (a :: k -> *) (b :: k -> *) = Foo

data Thing a b = Thing (Foo a (Const b))
$(makePrisms ''Thing)
```

... with `-ddump-splices` yields:
```
[1 of 1] Compiling Test             ( Test.hs, Test.o )
Test.hs:9:3-20: Splicing declarations
    makePrisms ''Thing
  ======>
    _Thing ::
      forall a_a3qw b_a3qx k_a3vt a_a74S b_a74T.
      Iso (Thing a_a74S b_a74T) (Thing a_a3qw b_a3qx) (Foo a_a74S (Const b_a74T :: k_a3vt
                                                                                   -> GHC.Types.Type)) (Foo a_a3qw (Const b_a3qx :: k_a3vt
                                                                                                                                    -> GHC.Types.Type))
    _Thing
      = (iso (\ (Thing x1_a74U) -> x1_a74U)) (\ x1_a74V -> Thing x1_a74V)
    {-# INLINE _Thing #-}

Test.hs:9:3: error:
    • These kind and type variables: a_a3qw b_a3qx k_a3vt a_a74S b_a74T
      are out of dependency order. Perhaps try this ordering:
        k_a3vt (a_a3qw :: k0 -> *) b_a3qx (a_a74S :: k0 -> *) b_a74T
    • In the type signature:
        _Thing :: forall a_a3qw b_a3qx k_a3vt a_a74S b_a74T.
                  Iso (Thing a_a74S b_a74T) (Thing a_a3qw b_a3qx) (Foo a_a74S (Const b_a74T :: k_a3vt
                                                                                               -> GHC.Types.Type)) (Foo a_a3qw (Const b_a3qx :: k_a3vt
                                                                                                                                                -> GHC.Types.Type))
  |
9 | $(makePrisms ''Thing)
```

One notices that the type signature starts with `forall a b k a' b'. ...`, which gets it into trouble, as the kinds of `a` and `b` are `k -> *` (i.e. `k -> Type`).

Looking at `makeFieldOptic` in `Control.Lens.Internal.FieldTH`, I can't easily tell why this would be the case.

**Comment by RyanGlScott** [comment]
I had a brief look into why this happens. There is no single line of code that is the culprit, but the general theme is that when we are constructing the `Iso` type, we have the following information in hand:

* `Thing a b`
* `Foo a (Const (b :: k -> Type))`

We then attempt to quantify over the type variables in these two types. It is critical that `k` appear before `a` in the `forall`, since `a :: k -> Type`, but we do not have this information available to us. As a result, we end up with an ill scoped `forall`.

What's curious is that we know that `k` appears in the kind of `b`, but `a`. The reason we know about `b`'s kind is because of how TH reifies `Thing`:

```
λ> putStrLn $(reify ''Thing >>= stringE . pprint)
data Test.Thing (a_0 :: k_1 -> *) (b_2 :: *)
    = Test.Thing (Test.Foo a_0
                           (Data.Functor.Const.Const b_2 :: k_1 -> *))
```

In fact, here we discover that `k` _does_ appear in the kind of `a`. So why do we end up with `Thing a b` instead of `Thing (a :: k -> Type) (b :: Type)`? It's because of the [`datatypeType`](https://hackage.haskell.org/package/th-abstraction-0.3.2.0/docs/Language-Haskell-TH-Datatype.html#v:datatypeType) function from `th-abstraction`, which `lens` uses in various places. `datatypeType` strips kind signatures off from the type parameter arguments to a data type, which loses valuable information _vis-à-vis_ scoping.

I can think of two possible ways to fix this:

1. Plumb through the [`datatypeVars`](https://hackage.haskell.org/package/th-abstraction-0.3.2.0/docs/Language-Haskell-TH-Datatype.html#v:datatypeVars) to the parts of `lens`' TH machinery that construct type signatures. `datatypeVars` does the hard work of computing the right scoping order for you.
2. Write a function that strips away all explicit kind signatures in a `Type`, and invoke that function on `Foo a (Const (b :: k -> Type))` to get `Foo a (Const b)`. That way, when we quantify over the type variables at the end, we won't even mention `k` in the first place, which prevents us from putting it out of scoping order.

(1) is the more principled fix, but it would likely take a lot of work to install the plumbing it requires. (2) is a bit of a hack, but it would likely be easier to implement.

**Comment by RyanGlScott** [comment]
By the way, a workaround for this issue is to use `declarePrisms` (which performs no TH reification) instead of `makePrisms`:

```hs
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PolyKinds #-}
module Test where
import Control.Lens

data Foo (a :: k -> *) (b :: k -> *) = Foo

$(declarePrisms [d| data Thing a b = Thing (Foo a (Const b)) |])
```

**Comment by jamespayor** [comment]
Yeah; I'd have mixed feelings about options (1) vs (2).
Option (2) is essentially leaving GHC to infer what kind variables are in play and to add them, whereas option (1) is trying to do that work yourself based on the reified types.

My guess is that option (2) should be safe and work whenever option (1) works, but I don't have a clear argument for why. Mostly it's that GHC has all the information that you do during reification, and is more likely to get it correct than you are manually.

I imagine failure cases where you accidentally quantify over `k1` and `k2` separately, even though the type of the optic demands that they be the same. And whilst GHC would have picked that up and collapsed it to just quantifying over `k`, your TH rendering as a `forall k1 k2 ...` might result in an error.

**Comment by RyanGlScott** [comment]
> Option (2) is essentially leaving GHC to infer what kind variables are in play and to add them, whereas option (1) is trying to do that work yourself based on the reified types.

Indeed. Option (2) is actually a slightly less radical version of a hypothetical option (3), which I omitted in https://github.com/ekmett/lens/issues/917#issuecomment-611822643 for fear of it being too extreme. Namely, option (3) is to simply not generate explicit `forall`s at all. This is even easier to implement than options (1) or (2), but at the downside of losing any guarantees about the order of type variables with respect to `TypeApplications`.

Then again, is the _current_ order of type variables in `lens`' TH machinery specified anywhere? If not, then we have some leeway in changing the order if the resulting code would be cleaner.

> My guess is that option (2) should be safe and work whenever option (1) works

Likely so. It's possible that there could be obscure programs that would break without the presence of an explicit kind signature to fix it, but I can't think of an example of such a program off the top of my head. 

> I imagine failure cases where you accidentally quantify over `k1` and `k2` separately, even though the type of the optic demands that they be the same. And whilst GHC would have picked that up and collapsed it to just quantifying over `k`, your TH rendering as a `forall k1 k2 ...` might result in an error.

I'm not sure I follow what you're saying here. Can you give an example that might fail in such a way?

**Comment by jamespayor** [comment]
If I'm allowed to use GADTs, it's relatively easy to construct an example. Here's one that currently fails:
```haskell
data Foo (a :: k -> Type) (b :: k -> Type) where
  Foo :: Foo (a :: Type -> Type) b
$(makePrisms ''Foo)
```

```
error:
    • Couldn't match type ‘k’ with ‘*’
      ‘k’ is a rigid type variable bound by
        the type signature for:
          _Foo :: forall k k1 (a :: k -> *) (b :: k -> *) (a1 :: k1 -> *)
                         (b1 :: k1 -> *) k2.
                  (k2 ~ *) =>
                  Prism (Foo a1 b1) (Foo a b) () ()
        at /Users/james/git/lol/typechecker/src/Language/Lol/Executable/REPL.hs:17:3-18
      Expected type: p () (f ()) -> p (Foo a1 b1) (f (Foo a b))
        Actual type: p () (f ()) -> p (Foo a1 b1) (f (Foo a0 b0))
    • In the expression:
        (prism (\ () -> Foo))
          (\ x_a3Sze -> case x_a3Sze of { Foo -> Right () })
      In an equation for ‘_Foo’:
          _Foo
            = (prism (\ () -> Foo))
                (\ x_a3Sze -> case x_a3Sze of { Foo -> Right () })
    • Relevant bindings include
        _Foo :: Prism (Foo a1 b1) (Foo a b) () ()
          (bound at /Users/james/git/lol/typechecker/src/Language/Lol/Executable/REPL.hs:17:3)
   |
17 | $(makePrisms ''Foo)
```

The problem is that if you go and just parse the type `Foo (a :: k -> Type) (b :: k -> Type)`, you may end up quantifying over too much. In this case, the `Foo` constructor actually restricts `k` to be `Type`.

I originally was trying to have a non-GADT case in mind that had similar problems when you try to work out which kind variables to quantify over. But I haven't succeeded in coming up with a concrete example there.

In any case, this GADT example would work if not for the explicit kind quantification being added by the TH code.

**Comment by jamespayor** [comment]
A simplification that still fails:
```haskell
data Foo (a :: k) where
  Foo :: Foo (a :: Type)
$(makePrisms ''Foo)
```

**Comment by jamespayor** [comment]
You could probably argue that these aren't deserving of proper treatment in a sense, but the main note is that these would just typecheck if not for quantifying over `k`.
(And I also recall having stripped kind variables for reasons like this in some TH of my own, and that seeming correct to me at the time for related reasons.)

**Comment by RyanGlScott** [comment]
Thanks, that's a good example to bear in mind. This leads me to believe that (1) is probably the most robust option. It will likely require a fair bit of refactoring of `lens`' TH internals to accomplish, but I think the end result would be worth it.

**Comment by RyanGlScott** [comment]
I made another attempt at fixing this, and it ended up being not quite as invasive as I had previously feared. See #945.
