### ISSUE TITLE
each :: IndexedTraversable ?

### ISSUE THREAD

**Issue by amesgen** [ekmett/lens#968]
I played around with `optics`, and I really liked that it has

```haskell
class Each i s t a b | s -> i a, t -> i b, s b -> t, t a -> s where
  each :: IxTraversal i s t a b
```

which is "just better", apart from backwards compatibility. In particular, `each` is shorter than `itraversed`, and the latter does not support `Text`/`Bytestring`/`Either a a`/tuples.

What about changing this in `lens` too, maybe in lens 5? This should be a mostly mechanical translation (can create a PR for this).

**Comment by phadej** [comment]
ping @ekmett 

I have no strong opinion either way.

**Comment by ekmett** [comment]
`each` was originally indexed in `lens`. The main of it was that it made it harder for users to implement at their own types, because now they had to understand how to make an indexed traversal, which is an appreciable bar to entry. 

On top of that it led to nonsensical/noncanonical choices of indices for things like tuples, 0-based, 1-based? why? do we index the _2 with a 0 for position or a 1 for index in the tuple? so we backed away from indexing `each`, `_2`, etc. and consciously removed the indices.

My concern would be that we'd be thrashing back to the old situation without doing anything to address the reasons why we stopped things them that way.

**Comment by amesgen** [comment]
> it led to nonsensical/noncanonical choices of indices

Ah yes, that is a good point which I did not have in mind.

Either way, this would be only a very minor convenience features, and I agree that the benefits don't outweigh the possible confusion when the choice of indices is nonobvious.
